Question 1:
Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 * C * D)/H]
Following are the fixed values of C and H:
C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated
sequence.
Example
Let us assume the following comma separated input sequence is given to the program:
100,150,180
The output of the program should be:
18,22,24

In [8]:
#Q1
import numpy as np
def calculate_Q(*D,C=50,H=30):
    Q=[]
    q=0
    for value in D:
        q=round(np.sqrt((2*C*value)/H))
        Q.append(q)
    return Q

calculate_Q(100,150,180)

[18, 22, 24]

Question 2:
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The
element value in the i-th row and j-th column of the array should be i*j.
Note: i=0,1.., X-1; j=0,1,¡Y-1.
Example
Suppose the following inputs are given to the program:
3,5
Then, the output of the program should be:
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [12]:
def gen_array(X,Y):
    arr=np.zeros((X,Y),dtype=int)
    for i in range(X):
        for j in range(Y):
            arr[i][j]=i*j
    return arr

X=int(input("Input the value of X : "))
Y=int(input("Input the value of Y : "))
print(gen_array(X,Y))

Input the value of X : 3
Input the value of Y : 5
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


Question 3:
Write a program that accepts a comma separated sequence of words as input and prints the
words in a comma-separated sequence after sorting them alphabetically.
Suppose the following input is supplied to the program:
without,hello,bag,world
Then, the output should be:
bag,hello,without,world

In [13]:
def sort_words(words):
    return sorted(words)

words=["without","hello","bag","world"]
sort_words(words)

['bag', 'hello', 'without', 'world']

Question 4:
Write a program that accepts a sequence of whitespace separated words as input and prints
the words after removing all duplicate words and sorting them alphanumerically.
Suppose the following input is supplied to the program:
hello world and practice makes perfect and hello world again
Then, the output should be:
again and hello makes perfect practice world

In [18]:
def sort_and_unique(string):
    words=string.split()
   
    result=[]
    for word in words:
        if word not in result:
            result.append(word)
    
    return " ".join(sorted(result))

string="hello world and practice makes perfect and hello world again"
print(sort_and_unique(string))

again and hello makes perfect practice world


Question 5:
Write a program that accepts a sentence and calculate the number of letters and digits.
Suppose the following input is supplied to the program:
hello world! 123
Then, the output should be:
LETTERS 10

DIGITS 3

In [21]:
import string

def count_letters_digits(s):
    digits=list(string.digits)
    letters=list(string.ascii_letters)
    letter_count=0
    digit_count=0
    for l in s:
        if l in digits:
            digit_count+=1
        elif l in letters:
            letter_count+=1
    return letter_count,digit_count

s="hello world! 123"
l,d=count_letters_digits(s)
print(f"LETTERS {l}\n\nDIGITS {d}")    


LETTERS 10

DIGITS 3


Question 6:
A website requires the users to input username and password to register. Write a program to
check the validity of password input by users.
Following are the criteria for checking the password:
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12
Your program should accept a sequence of comma separated passwords and will check them
according to the above criteria. Passwords that match the criteria are to be printed, each
separated by a comma.
Example
If the following passwords are given as input to the program:
ABd1234@1,a F1#,2w3E*,2We3345
Then, the output of the program should be:
ABd1234@1

In [23]:
def checkPassword(passwords):
    special_char = "$#@"
    for pwd in passwords:
        if len(pwd) <= 12 and len(pwd) >=6 :
            if any(i.isupper() for i in pwd):
                if any(i.islower() for i in pwd):
                    if any(i for i in pwd if i in special_char):
                        print(pwd)
passwords=["ABd1234@1","a F1#","2w3E*","2We3345"]
checkPassword(passwords)

ABd1234@1
