In [1]:
#Q1. Write a Python Program to find sum of array?
import numpy as np

array1=np.arange(1,10).reshape(3,3)
print(array1)
print(array1.sum())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


In [2]:
#Q2. Write a Python Program to find largest element in an array?
array2=np.array([[23,45,12],[56,6,20],[34,89,100]])
print(array2)
print(array2.max())

[[ 23  45  12]
 [ 56   6  20]
 [ 34  89 100]]
100


In [3]:
#Q3. Write a Python Program for array rotation?
array2=np.array([[23,45,12],[56,6,20],[34,89,100]])
print("Original Array : \n",array2)
print("\nArray after rotation : \n",np.transpose(array2))

Original Array : 
 [[ 23  45  12]
 [ 56   6  20]
 [ 34  89 100]]

Array after rotation : 
 [[ 23  56  34]
 [ 45   6  89]
 [ 12  20 100]]


In [5]:
#Q4. Write a Python Program to Split the array and add the first part to the end?
array3=np.array([12,34,56,78,20])
print("Original array : \n", array3)
print(f"The addition of the first item in the array :{array3[0]} and the last item in the array :{array3[-1]} is {array3[0]+array3[-1]}")

Original array : 
 [12 34 56 78 20]
The addition of the first item in the array :12 and the last item in the array :20 is 32


In [7]:
#Q5. Write a Python Program to check if given array is Monotonic?
def monotonic(x):
    dx = np.diff(x)
    return np.all(dx <= 0) or np.all(dx >= 0)

array4=np.arange(1,6)
array5=np.array([7,6,5,4,3,2,1])
array6=np.array([1,3,2,5])
print(monotonic(array4))
print(monotonic(array5))
print(monotonic(array6))

True
True
False
