In [1]:
#Q1. Write a Python Program to Add Two Matrices?
import numpy as np

X = np.matrix([[1,2,3], [4 ,5,6], [7 ,8,9]])

Y = np.matrix([[9,8,7], [6,5,4], [3,2,1]])

result =np.matrix([[0,0,0],[0,0,0],[0,0,0]])


def mat_add(a,b):
    for i in range(len(a)):
   # iterate through columns
       for j in range(len(a[0])):
           result[i][j] = a[i][j] + b[i][j]
    return result

mat_add(X,Y)




matrix([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])

In [2]:
#Q2. Write a Python Program to Multiply Two Matrices?
X = np.matrix([[1,2,3], [4 ,5,6], [7 ,8,9]])

Y = np.matrix([[9,8,7], [6,5,4], [3,2,1]])
def mat_mul(a,b):
    c=np.matmul(a,b)
    return c

print(mat_mul(X,Y))


[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [3]:
#Q3. Write a Python Program to Transpose a Matrix?
def transpose(X):
    result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]
    for r in result:
        print(r)

X = [[1,2,3], [4 ,5,6], [7 ,8,9]]

print("Original matrix : \n\n")
print(X)

print("\n\nTranspose of matrix : \n")
transpose(X)

Original matrix : 


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Transpose of matrix : 

[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [9]:
#Q4. Write a Python Program to Sort Words in Alphabetic Order?
list_of_words=['ball','apple','beast','zomato','swiggy','amazon']

def sort_words(lst):
    lst.sort()
    return lst

print(f"Original list of words : \n\n{list_of_words}")
print(f"\n\nSorted list of words : \n\n{sort_words(list_of_words)}")

Original list of words : 

['ball', 'apple', 'beast', 'zomato', 'swiggy', 'amazon']


Sorted list of words : 

['amazon', 'apple', 'ball', 'beast', 'swiggy', 'zomato']


In [13]:
#Q5. Write a Python Program to Remove Punctuation From a String?
import string

def remove_punc(strings):
    result=strings.translate(str.maketrans('', '', string.punctuation))
    return result


sample="My name is Latha. I'd love to meet up with my friends. The username is La1@se#. Let's see if this works...."
print(f"Original string : \n\n{sample}")
print(f"\nAfter removing the punctuations : \n\n{remove_punc(sample)}")

Original string : 

My name is Latha. I'd love to meet up with my friends. The username is La1@se#. Let's see if this works....

After removing the punctuations : 

My name is Latha Id love to meet up with my friends The username is La1se Lets see if this works
